"""Add data_consent column to users table

Revision ID: 90a18a7bc4bf
Revises: 
Create Date: 2024-06-18 21:04:12.250706

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a18a7bc4bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "data_consent",
                sa.Boolean(),
                server_default=sa.sql.expression.false(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("data_consent")

    # ### end Alembic commands ###
